// Generated by cpp4r: do not edit by hand
// clang-format off


#include "cpp4r/declarations.hpp"
#include <R_ext/Visibility.h>

// kendall_correlation.cpp
double kendall_cor_(const doubles & x, const doubles & y);
extern "C" SEXP _kendallknight_kendall_cor_(SEXP x, SEXP y) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(kendall_cor_(cpp4r::as_cpp<cpp4r::decay_t<const doubles &>>(x), cpp4r::as_cpp<cpp4r::decay_t<const doubles &>>(y)));
  END_CPP4R
}
// kendall_correlation.cpp
doubles pkendall_(doubles Q, int n);
extern "C" SEXP _kendallknight_pkendall_(SEXP Q, SEXP n) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(pkendall_(cpp4r::as_cpp<cpp4r::decay_t<doubles>>(Q), cpp4r::as_cpp<cpp4r::decay_t<int>>(n)));
  END_CPP4R
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_kendallknight_kendall_cor_", (DL_FUNC) &_kendallknight_kendall_cor_, 2},
    {"_kendallknight_pkendall_",    (DL_FUNC) &_kendallknight_pkendall_,    2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_kendallknight(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
